export const COUNT_PURCHASES_START = "COUNT_PURCHASES_START";
export const COUNT_PURCHASES_SUCCESS = "COUNT_PURCHASES_SUCCESS";
export const COUNT_PURCHASES_ERROR = "COUNT_PURCHASES_ERROR";

export const ADD_PRODUCTS_TO_LIST_START = "ADD_PRODUCTS_TO_LIST_START";
export const ADD_PRODUCTS_TO_LIST_SUCCESS = "ADD_PRODUCTS_TO_LIST_SUCCESS";
export const ADD_PRODUCTS_TO_LIST_ERROR = "ADD_PRODUCTS_TO_LIST_ERROR";
